AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: false
Gemspec/OrderedDependencies:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "test/**/*"
Metrics/LineLength:
  Enabled: false
Naming/RescuedExceptionsVariableName:
  PreferredName: exception
Style/AndOr:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Style/MethodDefParentheses:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
